### ISSUE TITLE
Make training code available?

### ISSUE THREAD

**Issue by JohnnyC08** [bhavitvyamalik/DialogTag#2]
I'm interested in reproducing the model in pytorch and am curious how you preprocessed the data and trained it. I didn't see any metrics reported and want to see what those look like as well! So, the training script would be nice to have as well!

Great repo by the way!

**Comment by creatorrr** [comment]
+1 @JohnnyC08 

It'd also be interesting to see if including context (conversation history / last utterances) improves the accuracy of predictions.

**Comment by JohnnyC08** [comment]
@creatorrr That's interesting.

How would you go about doing that? My first thought is using a rolling window and making a single block of text out of the elements of the window and assigning the label to the text block of the last element in the block.

How would you do it?

**Comment by creatorrr** [comment]
@JohnnyC08 I was thinking of something simpler, prepending dialog act labels of the last three utterances to the input vector when finetuning it. For example, take this conversation:
```yaml
A: Do you want to grab lunch? [Yes-No-Question]
B: Not really. [Dispreferred-answers]
A: Oh okay. [Response-Acknowledgement]
B: How about tomorrow? <<TO PREDICT>>
```
Then the input vector would be:
`[CLS] Yes-No-Question [SEP] Dispreferred-answers [SEP] Response-Acknowledgement [SEP] How about tomorrow? [SEP]`
